version: 2
jobs:
  vs-ponyc-release:
    docker:
      - image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder:release
    steps:
      - checkout
      - run: make clean test examples
  vs-ponyc-master:
    docker:
      - image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder:latest
    steps:
      - checkout
      - run: make clean test examples

workflows:
  version: 2
  commit:
    jobs:
      - vs-ponyc-release
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - vs-ponyc-master
